Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:

beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
Writing entries...
Writing entries...
Writing entries...
Writing entries...
Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4
         * *
          * (m/h/d/dM/MY), UTC>
        >
beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
Writing entries...
Writing entries...
Writing entries...
Writing entries...
Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4
         * *
          * (m/h/d/dM/MY), UTC>
        >
beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
Writing entries...
Writing entries...
Writing entries...
Writing entries...
Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4
         * *
          * (m/h/d/dM/MY), UTC>
        >
beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
Writing entries...
Writing entries...
Writing entries...
Writing entries...
Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4
         * *
          * (m/h/d/dM/MY), UTC>
        >
beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
Database gave error: ProgrammingError(1146, "Table 'xxscan.django_celery_beat_periodictasks' doesn't exist")
Traceback (most recent call last):
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'xxscan.django_celery_beat_periodictasks' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 255, in schedule_changed
    last, ts = self._last_timestamp, self.Changes.last_change()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django_celery_beat/models.py", line 252, in last_change
    return cls.objects.get(ident=1).last_update
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/django/xs_venv/lib64/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'xxscan.django_celery_beat_periodictasks' doesn't exist")
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
